apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: waldur-helm-testing
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      gitlab:
        project: waldur/waldur-helm
        api: https://code.opennodecloud.com/
        tokenRef:
          secretName: gitlab-token-waldur-group
          key: token
        pullRequestState: opened
        insecure: true
      requeueAfterSeconds: 1800
  template:
    metadata:
      name: 'waldur-helm-{{.number}}'
    spec:
      source:
        repoURL: https://code.opennodecloud.com/waldur/waldur-helm.git
        path: waldur/
        targetRevision: '{{.head_sha}}'
        helm:
          valueFiles:
          - test/values.yaml
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: waldur
