image.repository: "minio/minio"
image.tag: "RELEASE.2020-11-06T23-17-07Z"
mcImage.repository: "minio/mc"
mcImage.tag: "RELEASE.2020-10-03T02-54-56Z"

accessKey: ""
secretKey: ""
serviceAccount:
  name: minio-account
persistence:
  enabled: true
  size: 5Gi
## Uncomment if you need storage distribution
#  mode: distributed
#  replicas: 4
ingress:
  enabled: true
  hosts:
    - minio.host
defaultBucket:
  enabled: true
  name: data
## Uncomment if you want to change memory request
#  resources:
#    requests:
#      memory: 1Gi
