nameOverride: "waldur"

postgresql:
  database: waldur
  username: waldur
  password: waldur
  postgresPassword: postgres
  repmgrPassword: repmgr
  replicaCount: 3
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql-repmgr
    tag: "16.4.0-debian-12-r26"
pgpool:
  image:
    registry: docker.io
    repository: bitnamilegacy/pgpool
    tag: "4.6.2-debian-12-r7"

# TODO: remove after migration to a stable RabbitMQ and PostgreSQL images from bitnamilegacy repo
global:
  security:
    allowInsecureImages: true
