nameOverride: "waldur"

auth:
  username: "waldur"
  password: "waldur"
  database: "waldur"

primary:
  persistence:
    size: "10Gi"
  resources:
    requests:
      memory: "1024Mi"
      cpu: "500m"
    limits:
      memory: "2048Mi"
      cpu: "1000m"

image:
  registry: "docker.io"
  repository: bitnamilegacy/postgresql
  tag: "16.4.0-debian-12-r19"

metrics:
  enabled: false
  image:
    registry: "docker.io"
    repository: bitnamilegacy/postgres-exporter
    tag: 0.17.1-debian-12-r14

# TODO: remove after migration to a stable RabbitMQ and PostgreSQL images from bitnamilegacy repo
global:
  security:
    allowInsecureImages: true
