nameOverride: "waldur"

postgresql:
  database: waldur
  username: waldur
  password: waldur
  postgresPassword: postgres
  repmgrPassword: repmgr
  replicaCount: 3
  image:
    tag: "16.4.0-debian-12-r26"
pgpool:
  image:
    tag: "4.5.4-debian-12-r2"
