nameOverride: "waldur"

postgresql:
  database: waldur
  username: waldur
  password: waldur
  postgresPassword: postgres
  repmgrPassword: repmgr
  replicaCount: 3
  image:
    tag: "12.15.0-debian-11-r12"
pgpool:
  image:
    tag: "4.4.3-debian-11-r6"
