image:
  registry: "docker.io"
  repository: "bitnamilegacy/rabbitmq"
  tag: "4.1.3-debian-12-r1"

replicaCount: 3
persistence:
  enabled: true
  size: "10Gi"
  storageClass: ""
auth:
  username: "waldur"
  password: "waldur"

extraPlugins: "rabbitmq_auth_backend_ldap rabbitmq_mqtt rabbitmq_web_mqtt rabbitmq_management rabbitmq_web_stomp rabbitmq_stomp"

extraContainerPorts:
- name: mqtt
  containerPort: 1883
  protocol: TCP
- name: stomp
  containerPort: 61613
  protocol: TCP
- name: mqtt-websocket
  containerPort: 15675
  protocol: TCP
- name: stomp-websocket
  containerPort: 15674
  protocol: TCP

service:
  extraPorts:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: mqtt
  - name: stomp
    protocol: TCP
    port: 61613
    targetPort: stomp
  - name: mqtt-websocket
    protocol: TCP
    port: 15675
    targetPort: mqtt-websocket
  - name: stomp-websocket
    protocol: TCP
    port: 15674
    targetPort: stomp-websocket

networkPolicy:
  extraIngress:
  - ports:
    - protocol: TCP
      containerPort: 1883
      port: 1883
    - protocol: TCP
      containerPort: 15675
      port: 15675

resources:
  requests:
    cpu: 1
    memory: 2048Mi
  limits:
    cpu: 2
    memory: 4096Mi

clustering:
  forceBoot: true

# TODO: remove after migration to a stable RabbitMQ and PostgreSQL images from bitnamilegacy repo
global:
  security:
    allowInsecureImages: true
