replicaCount: 3
persistentVolume:
  enabled: true
  name: "rmq-data"
  size: "10Gi"
  storageClass: ""
rabbitmqUsername: "waldur"
rabbitmqPassword: "waldur"
prometheus:
  operator:
    enabled: false
