image:
  registry: "docker.io"
  repository: "bitnami/rabbitmq"
  tag: "4.0.2-debian-12-r0"

replicaCount: 3
persistence:
  enabled: true
  size: "10Gi"
  storageClass: ""
auth:
  username: "waldur"
  password: "waldur"

resources:
  requests:
    cpu: 1
    memory: 512Mi
  limits:
    cpu: 2
    memory: 1024Mi

clustering:
  forceBoot: true
