{{ if and (and .Values.ingress.tls.enabled (.Values.ingress.tls.source | eq "secret")) (not .Values.ingress.tls.customMastermindSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: api-certificate
type: Opaque
data:
{{ $secretsDirTemp := .Values.ingress.tls.secretsDir | printf "%s/*"}}
{{ (.Files.Glob $secretsDirTemp).AsSecrets | indent 2 }}
{{ end }}
