apiVersion: v1
kind: ConfigMap
metadata:
  name: mastermind-config-features-json
data:
  features.json: |
    {
      {{ if has "compliancy" .Values.waldur.features }}
        "marketplace.checklist": true,
      {{ end }}
      {{ if has "conceal_prices" .Values.waldur.features }}
        "marketplace.conceal_prices": true,
      {{ end }}
      {{ if has "hide_volume_type_selector" .Values.waldur.features }}
        "openstack.hide_volume_type_selector": true,
      {{ end }}
      {{ if has "disable_user_ssh_keys" .Values.waldur.features }}
        "user.ssh_keys": false,
      {{ end }}
      {{ if has "marketplace.tos" .Values.waldur.features }}
        "marketplace.terms_of_service": true,
      {{ end }}
      {{ if has "show_industry_flag" .Values.waldur.features }}
        "project.show_industry_flag": true,
      {{ end }}
      {{ if has "enable_project_oecd_code" .Values.waldur.features }}
        "project.oecd_fos_2007_code": true,
      {{ end }}
      {{ if has "project.show_description_in_create_dialog" .Values.waldur.features }}
        "project.show_description_in_create_dialog": true,
      {{ end }}
      {{ if has "project.show_type_in_create_dialog" .Values.waldur.features }}
        "project.show_type_in_create_dialog": true,
      {{ end }}
      {{ if has "project.show_end_date_in_create_dialog" .Values.waldur.features }}
        "project.show_end_date_in_create_dialog": true,
      {{ end }}
      {{ if has "project.show_image_in_create_dialog" .Values.waldur.features }}
        "project.show_image_in_create_dialog": true,
      {{ end }}
      {{ if has "organization_domain_visible" .Values.waldur.features }}
        "customer.show_domain": true,
      {{ end }}
      {{ if has "invitation_conceal_civil_number" .Values.waldur.features }}
        "invitations.conceal_civil_number": true,
      {{ end }}
      {{ if not (has "billing" .Values.waldur.features) }}
        "customer.hide_organization_billing_step": true,
      {{ end }}
      {{ if has "marketplace_show_experimental_ui_components" .Values.waldur.features }}
        "marketplace.show_experimental_ui_components": true,
      {{ end }}
      {{ if has "marketplace_review" .Values.waldur.features }}
        "marketplace.review": true,
      {{ end }}
      {{ if has "marketplace_catalogue_only" .Values.waldur.features }}
        "marketplace.catalogue_only": true,
      {{ end }}
      {{ if has "marketplace_offering_document" .Values.waldur.features }}
        "marketplace.offering_document": true,
      {{ end }}
      {{ if has "user_show_username" .Values.waldur.features }}
        "user.show_username": true,
      {{ end }}
      {{ if has "marketplace_show_resource_end_date" .Values.waldur.features }}
        "marketplace.show_resource_end_date": true,
      {{ end }}
        "marketplace.import_resources": true,
        "user.notifications": true,
        "project.estimated_cost": true,
        "support.users": true,
        "support.shared_providers": true
    }
