apiVersion: v1
kind: ConfigMap
metadata:
  name: homeport-vars-config
data:
  {{ $fpath := "" }}
  {{ if .Values.waldur.whitelabeling.logo96Path }}
    {{ $fpath = .Values.waldur.whitelabeling.logo96Path }}
  logo-96x96.png: |
{{ .Files.Get $fpath | b64enc | indent 4 }}
  {{ else if .Values.waldur.whitelabeling.logo96BlobPath }}
    {{ $fpath = .Values.waldur.whitelabeling.logo96BlobPath }}
  logo-96x96.png: |
{{ .Files.Get $fpath | indent 4 }}
  {{ end }}

  {{ if .Values.waldur.whitelabeling.logo144Path }}
    {{ $fpath = .Values.waldur.whitelabeling.logo144Path }}
  logo-144x144.png: |
{{ .Files.Get $fpath | b64enc | indent 4 }}
  {{ else if .Values.waldur.whitelabeling.logo144BlobPath }}
    {{ $fpath = .Values.waldur.whitelabeling.logo144BlobPath }}
  logo-144x144.png: |
{{ .Files.Get $fpath | indent 4 }}
  {{ end }}

  {{ if .Values.waldur.whitelabeling.logo192Path }}
    {{ $fpath = .Values.waldur.whitelabeling.logo192Path }}
  logo-192x192.png: |
{{ .Files.Get $fpath | b64enc | indent 4 }}
  {{ else if .Values.waldur.whitelabeling.logo192BlobPath }}
    {{ $fpath = .Values.waldur.whitelabeling.logo192BlobPath }}
  logo-192x192.png: |
{{ .Files.Get $fpath | indent 4 }}
  {{ end }}

  {{ if .Values.waldur.whitelabeling.faviconPath }}
    {{ $fpath = .Values.waldur.whitelabeling.faviconPath }}
  favicon.ico: |
{{ .Files.Get $fpath | b64enc | indent 4 }}
  {{ else if .Values.waldur.whitelabeling.faviconBlobPath }}
    {{ $fpath = .Values.waldur.whitelabeling.faviconBlobPath }}
  favicon.ico: |
{{ .Files.Get $fpath | indent 4 }}
  {{ end }}

  {{ if .Values.waldur.whitelabeling.manifestJsonPath }}
    {{ $fpath = .Values.waldur.whitelabeling.manifestJsonPath }}
  manifest.json: |
{{ .Files.Get $fpath | indent 4 }}
  {{end}}

  {{ if .Values.waldur.whitelabeling.privacyHtmlPath }}
    {{ $fpath = .Values.waldur.whitelabeling.privacyHtmlPath }}
  privacy.html: |
{{ .Files.Get $fpath | indent 4 }}
  {{ end }}

  {{ if .Values.waldur.whitelabeling.tosHtmlPath }}
    {{ $fpath = .Values.waldur.whitelabeling.tosHtmlPath }}
  tos.html: |
{{ .Files.Get $fpath | indent 4 }}
  {{ end }}
