{{ if or .Values.waldur.mastermindTemplating.mastermindTemplatesPath .Values.waldur.mastermindTemplating.mastermindTemplates }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mastermind-template-config
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
data:
  mastermind-templates.yaml: |
{{ if .Values.waldur.mastermindTemplating.mastermindTemplates }}
{{ toYaml .Values.waldur.mastermindTemplating.mastermindTemplates | indent 4 }}
{{ else }}
{{ .Files.Get .Values.waldur.mastermindTemplating.mastermindTemplatesPath | indent 4 }}
{{ end }}

{{ end }}
