apiVersion: v1
kind: ConfigMap
metadata:
  name: mastermind-config-permissions-override-yaml
data:
  permissions-override.yaml: |
    - role: CUSTOMER.OWNER
      {{ if has "academic_domain" .Values.waldur.features }}
      description: PI
      {{ end }}
      {{ if has "academic_shared_domain" .Values.waldur.features }}
      description: Resource allocator
      {{ end }}
      add_permissions:
        {{ if has "owner_can_register_service_provider" .Values.waldur.features }}
        - SERVICE_PROVIDER.REGISTER
        {{ end }}
        {{ if not (has "only_staff_manages_services" .Values.waldur.features) }}
        - ORDER.APPROVE
        {{ end }}
        {{ if has "owners_can_manage_owners" .Values.waldur.features }}
        - CUSTOMER.CREATE_PERMISSION
        - CUSTOMER.UPDATE_PERMISSION
        - CUSTOMER.DELETE_PERMISSION
        {{ end }}
        {{ if has "owner_can_manage_customers" .Values.waldur.features }}
        - CUSTOMER.CREATE
        - CUSTOMER.UPDATE
        - CUSTOMER.DELETE
        {{ end }}
      drop_permissions:
        {{ if not (has "owner_can_register_service_provider" .Values.waldur.features) }}
        - SERVICE_PROVIDER.REGISTER
        {{ end }}
        {{ if has "only_staff_manages_services" .Values.waldur.features }}
        - ORDER.APPROVE
        {{ end }}
        {{ if not (has "owners_can_manage_owners" .Values.waldur.features) }}
        - CUSTOMER.CREATE_PERMISSION
        - CUSTOMER.UPDATE_PERMISSION
        - CUSTOMER.DELETE_PERMISSION
        {{ end }}
        {{ if not (has "owner_can_manage_customers" .Values.waldur.features) }}
        - CUSTOMER.CREATE
        - CUSTOMER.UPDATE
        - CUSTOMER.DELETE
        {{ end }}

    - role: PROJECT.ADMIN
      {{ if has "academic_domain" .Values.waldur.features }}
      description: Member
      {{ end }}
      {{ if has "academic_shared_domain" .Values.waldur.features }}
      description: Co-PI
      {{ end }}
      add_permissions:
        {{ if has "admin_can_approve_order" .Values.waldur.features }}
        - ORDER.APPROVE
        {{ end }}
      drop_permissions:
        {{ if not (has "admin_can_approve_order" .Values.waldur.features) }}
        - ORDER.APPROVE
        {{ end }}

    - role: PROJECT.MANAGER
      {{ if has "academic_domain" .Values.waldur.features }}
      description: Co-PI
      {{ end }}
      {{ if has "academic_shared_domain" .Values.waldur.features }}
      description: PI
      {{ end }}
      add_permissions:
        {{ if has "manager_can_approve_order" .Values.waldur.features }}
        - ORDER.APPROVE
        {{ end }}
      drop_permissions:
        {{ if not (has "manager_can_approve_order" .Values.waldur.features) }}
        - ORDER.APPROVE
        {{ end }}

    - role: PROJECT.MEMBER
      {{ if has "enable_project_member_role" .Values.waldur.features }}
      is_active: true
      {{ else }}
      is_active: false
      {{ end }}
      {{ if has "academic_domain" .Values.waldur.features }}
      description: Guest
      {{ end }}
      {{ if has "academic_shared_domain" .Values.waldur.features }}
      description: Member
      {{ end }}
