apiVersion: v1
kind: ConfigMap
metadata:
  name: mastermind-config-permissions-override-yaml
data:
  permissions-override.yaml: |
    - role: CUSTOMER.OWNER
      {{ if has "academic_domain" .Values.waldur.features }}
      description: PI
      {{ end }}
      {{ if has "academic_shared_domain" .Values.waldur.features }}
      description: Resource allocator
      {{ end }}
      {{ if has "customer_owner" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}
      add_permissions:
        {{ if has "owner_can_register_service_provider" .Values.waldur.features }}
        - SERVICE_PROVIDER.REGISTER
        {{ end }}
        {{ if not (has "owner_can_approve_order" .Values.waldur.features) }}
        - ORDER.APPROVE
        {{ end }}
        {{ if has "owners_can_manage_owners" .Values.waldur.features }}
        - CUSTOMER.CREATE_PERMISSION
        - CUSTOMER.UPDATE_PERMISSION
        - CUSTOMER.DELETE_PERMISSION
        {{ end }}
        {{ if has "owner_can_manage_customers" .Values.waldur.features }}
        - CUSTOMER.CREATE
        - CUSTOMER.UPDATE
        - CUSTOMER.DELETE
        {{ end }}
      drop_permissions:
        {{ if not (has "owner_can_register_service_provider" .Values.waldur.features) }}
        - SERVICE_PROVIDER.REGISTER
        {{ end }}
        {{ if has "owner_can_approve_order" .Values.waldur.features }}
        - ORDER.APPROVE
        {{ end }}
        {{ if not (has "owners_can_manage_owners" .Values.waldur.features) }}
        - CUSTOMER.CREATE_PERMISSION
        - CUSTOMER.UPDATE_PERMISSION
        - CUSTOMER.DELETE_PERMISSION
        {{ end }}
        {{ if not (has "owner_can_manage_customers" .Values.waldur.features) }}
        - CUSTOMER.CREATE
        - CUSTOMER.UPDATE
        - CUSTOMER.DELETE
        {{ end }}

    - role: CUSTOMER.MANAGER
      {{ if has "customer_manager" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}

    - role: CUSTOMER.SUPPORT
      {{ if has "customer_support" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}

    - role: PROJECT.ADMIN
      {{ if has "academic_domain" .Values.waldur.features }}
      description: Member
      {{ end }}
      {{ if has "academic_shared_domain" .Values.waldur.features }}
      description: Co-PI
      {{ end }}
      {{ if has "project_admin" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}
      add_permissions:
        {{ if has "admin_can_approve_order" .Values.waldur.features }}
        - ORDER.APPROVE
        {{ end }}
      drop_permissions:
        {{ if not (has "admin_can_approve_order" .Values.waldur.features) }}
        - ORDER.APPROVE
        {{ end }}

    - role: PROJECT.MANAGER
      {{ if has "academic_domain" .Values.waldur.features }}
      description: Co-PI
      {{ end }}
      {{ if has "academic_shared_domain" .Values.waldur.features }}
      description: PI
      {{ end }}
      {{ if has "project_manager" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}
      add_permissions:
        {{ if has "manager_can_approve_order" .Values.waldur.features }}
        - ORDER.APPROVE
        {{ end }}
      drop_permissions:
        {{ if not (has "manager_can_approve_order" .Values.waldur.features) }}
        - ORDER.APPROVE
        {{ end }}

    - role: PROJECT.MEMBER
      {{ if has "project_member" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}
      {{ if has "academic_domain" .Values.waldur.features }}
      description: Guest
      {{ else }}
      description: Project member
      {{ end }}

    - role: OFFERING.MANAGER
      {{ if has "offering_manger" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}

    - role: CALL.REVIEWER
      {{ if has "call_reviewer" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}

    - role: CALL.MANAGER
      {{ if has "call_manager" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}

    - role: PROPOSAL.MANAGER
      {{ if has "proposal_manager" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}
