apiVersion: v1
kind: ConfigMap
metadata:
  name: mastermind-config-permissions-override-yaml
data:
  permissions-override.yaml: |
    - role: CUSTOMER.OWNER
      {{- if hasKey .Values.waldur.customRoleDescriptions "CUSTOMER.OWNER" }}
      description: {{ index .Values.waldur.customRoleDescriptions "CUSTOMER.OWNER" }}
      {{- else }}
      {{ if has "academic_domain" .Values.waldur.features }}
      description: PI
      {{ end }}
      {{ if has "academic_shared_domain" .Values.waldur.features }}
      description: Resource allocator
      {{ end }}
      {{- end }}
      {{ if has "customer_owner" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}
      add_permissions:
        {{ if has "owner_can_register_service_provider" .Values.waldur.features }}
        - SERVICE_PROVIDER.REGISTER
        {{ end }}
        {{ if not (has "owner_can_approve_order" .Values.waldur.features) }}
        - ORDER.APPROVE
        {{ end }}
        {{ if or (has "owners_can_manage_owners" .Values.waldur.features) (has "owner_can_manage_customers" .Values.waldur.features) }}
        - CUSTOMER.CREATE_PERMISSION
        - CUSTOMER.UPDATE_PERMISSION
        - CUSTOMER.DELETE_PERMISSION
        {{ end }}
      drop_permissions:
        {{ if not (has "owner_can_register_service_provider" .Values.waldur.features) }}
        - SERVICE_PROVIDER.REGISTER
        {{ end }}
        {{ if has "owner_can_approve_order" .Values.waldur.features }}
        - ORDER.APPROVE
        {{ end }}
        {{ if not (or (has "owners_can_manage_owners" .Values.waldur.features) (has "owner_can_manage_customers" .Values.waldur.features)) }}
        - CUSTOMER.CREATE_PERMISSION
        - CUSTOMER.UPDATE_PERMISSION
        - CUSTOMER.DELETE_PERMISSION
        {{ end }}

    - role: CUSTOMER.MANAGER
      {{ if has "customer_manager" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}
      {{- if hasKey .Values.waldur.customRoleDescriptions "CUSTOMER.MANAGER" }}
      description: {{ index .Values.waldur.customRoleDescriptions "CUSTOMER.MANAGER" }}
      {{- end }}

    - role: CUSTOMER.SUPPORT
      {{ if has "customer_support" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}
      {{- if hasKey .Values.waldur.customRoleDescriptions "CUSTOMER.SUPPORT" }}
      description: {{ index .Values.waldur.customRoleDescriptions "CUSTOMER.SUPPORT" }}
      {{- end }}

    - role: PROJECT.ADMIN
      {{- if hasKey .Values.waldur.customRoleDescriptions "PROJECT.ADMIN" }}
      description: {{ index .Values.waldur.customRoleDescriptions "PROJECT.ADMIN" }}
      {{- else }}
      {{ if has "academic_domain" .Values.waldur.features }}
      description: Member
      {{ end }}
      {{ if has "academic_shared_domain" .Values.waldur.features }}
      description: Co-PI
      {{ end }}
      {{- end }}
      {{ if has "project_admin" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}
      add_permissions:
        {{ if has "admin_can_approve_order" .Values.waldur.features }}
        - ORDER.APPROVE
        {{ end }}
      drop_permissions:
        {{ if not (has "admin_can_approve_order" .Values.waldur.features) }}
        - ORDER.APPROVE
        {{ end }}

    - role: PROJECT.MANAGER
      {{- if hasKey .Values.waldur.customRoleDescriptions "PROJECT.MANAGER" }}
      description: {{ index .Values.waldur.customRoleDescriptions "PROJECT.MANAGER" }}
      {{- else }}
      {{ if has "academic_domain" .Values.waldur.features }}
      description: Co-PI
      {{ end }}
      {{ if has "academic_shared_domain" .Values.waldur.features }}
      description: PI
      {{ end }}
      {{- end }}
      {{ if has "project_manager" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}
      add_permissions:
        {{ if and (hasKey .Values.waldur.customRolePermissions "PROJECT.MANAGER") (hasKey (index .Values.waldur.customRolePermissions "PROJECT.MANAGER") "addPermissions") }}
        {{- toYaml (index .Values.waldur.customRolePermissions "PROJECT.MANAGER").addPermissions | nindent 8 }}
        {{ else if has "manager_can_approve_order" .Values.waldur.features }}
        - ORDER.APPROVE
        {{- end }}
      drop_permissions:
        {{ if and (hasKey .Values.waldur.customRolePermissions "PROJECT.MANAGER") (hasKey (index .Values.waldur.customRolePermissions "PROJECT.MANAGER") "dropPermissions") }}
        {{- toYaml (index .Values.waldur.customRolePermissions "PROJECT.MANAGER").dropPermissions | nindent 8 }}
        {{ else if not (has "manager_can_approve_order" .Values.waldur.features) }}
        - ORDER.APPROVE
        {{- end }}

    - role: PROJECT.MEMBER
      {{- if hasKey .Values.waldur.customRoleDescriptions "PROJECT.MEMBER" }}
      description: {{ index .Values.waldur.customRoleDescriptions "PROJECT.MEMBER" }}
      {{- else }}
      {{ if has "academic_domain" .Values.waldur.features }}
      description: Guest
      {{ else }}
      description: Project member
      {{ end }}
      {{- end }}
      {{ if has "project_member" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}

    - role: OFFERING.MANAGER
      {{- if hasKey .Values.waldur.customRoleDescriptions "OFFERING.MANAGER" }}
      description: {{ index .Values.waldur.customRoleDescriptions "OFFERING.MANAGER" }}
      {{- end }}
      {{ if has "offering_manger" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}

    - role: CALL.REVIEWER
      {{- if hasKey .Values.waldur.customRoleDescriptions "CALL.REVIEWER" }}
      description: {{ index .Values.waldur.customRoleDescriptions "CALL.REVIEWER" }}
      {{- end }}
      {{ if has "call_reviewer" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}

    - role: CALL.MANAGER
      {{- if hasKey .Values.waldur.customRoleDescriptions "CALL.MANAGER" }}
      description: {{ index .Values.waldur.customRoleDescriptions "CALL.MANAGER" }}
      {{- end }}
      {{ if has "call_manager" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}

    - role: PROPOSAL.MANAGER
      {{- if hasKey .Values.waldur.customRoleDescriptions "PROPOSAL.MANAGER" }}
      description: {{ index .Values.waldur.customRoleDescriptions "PROPOSAL.MANAGER" }}
      {{- end }}
      {{ if has "proposal_manager" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}

    - role: CUSTOMER.CALL_ORGANIZER
      scope: call_organizer
      {{- if hasKey .Values.waldur.customRoleDescriptions "CALL.MANAGER" }}
      description: {{ index .Values.waldur.customRoleDescriptions "CALL.MANAGER" }}
      {{- else }}
      description: Organization call organizer
      {{- end }}
      {{ if has "call_organizer" .Values.waldur.disabledRoles }}
      is_active: false
      {{ else }}
      is_active: true
      {{ end }}
