{{- if eq .Values.ingress.className "nginx" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: waldur-security-headers
  labels:
    {{- include "waldur.labels" . | nindent 4 }}
data:
  {{- $customSentryUrl443 := "" }}
  {{- $customSentryUrl80 := "" }}
  {{- if .Values.waldur.homeport.customSentryURL }}
    {{- $customSentryUrl443 = (print .Values.waldur.homeport.customSentryURL ":443") }}
    {{- $customSentryUrl80 = (print .Values.waldur.homeport.customSentryURL ":80") }}
  {{- end }}
  Content-Security-Policy: "base-uri 'self'; object-src 'none'; media-src 'none'; script-src 'self' sentry.opnd.org {{ .Values.waldur.homeport.customSentryURL }} {{ .Values.waldur.homeport.matomoUrlBase }}; style-src 'self' 'unsafe-inline'; img-src 'self' *.tile.openstreetmap.org {{ .Values.apiHostname }} blob: data: ; connect-src 'self' {{ .Values.apiHostname }} {{ .Values.waldur.homeport.matomoUrlBase }} nominatim.openstreetmap.org:443 sentry.opnd.org:443 sentry.opnd.org:80 {{ $customSentryUrl80 }} {{ $customSentryUrl443 }}; font-src 'self' data: ; frame-src 'none'; frame-ancestors 'none'"
{{- end }}