{{ if has "SAML2" .Values.waldur.authMethods }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: waldur-saml2-conf-config
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
data:
{{ $configFile := .Values.waldur.saml2.dir | printf "%s/saml2.conf.py" }}
  saml2.conf.py: |-
{{ .Files.Get $configFile | indent 4 }}
{{ end }}
