apiVersion: v1
kind: ConfigMap
metadata:
  name: mastermind-config-permissions-yaml
data:
  permissions.yaml: |
    - role: CUSTOMER.OWNER
      {{ if has "academic_domain" .Values.waldur.features }}
      description: PI
      {{ end }}
      {{ if has "academic_shared_domain" .Values.waldur.features }}
      description: resource allocator
      {{ end }}
      permissions:
        {{ if has "owner_can_register_service_provider" .Values.waldur.features }}
        - SERVICE_PROVIDER.REGISTER
        {{ end }}
        {{ if not (has "only_staff_manages_services" .Values.waldur.features) }}
        - ORDER.APPROVE
        {{ end }}
        - OFFERING.UPDATE
        - OFFERING.UPDATE_THUMBNAIL
        - OFFERING.UPDATE_ATTRIBUTES
        - OFFERING.UPDATE_LOCATION
        - OFFERING.UPDATE_DESCRIPTION
        - OFFERING.UPDATE_OVERVIEW
        - OFFERING.UPDATE_OPTIONS
        - OFFERING.UPDATE_SECRET_OPTIONS
        - OFFERING.ADD_ENDPOINT
        - OFFERING.DELETE_ENDPOINT
        - OFFERING.UPDATE_COMPONENTS
        - OFFERING.PAUSE
        - OFFERING.UNPAUSE
        - OFFERING.ARCHIVE
        - OFFERING.DRY_RUN_SCRIPT
        - OFFERING.MANAGE_CAMPAIGN
        - OFFERING.MANAGE_USER_GROUP
        - ORDER.APPROVE_PRIVATE
        - ORDER_ITEM.APPROVE
        - ORDER_ITEM.REJECT
        - ORDER_ITEM.DESTROY
        - ORDER_ITEM.TERMINATE
        - RESOURCE.SET_END_DATE
        - RESOURCE.SET_USAGE
        - RESOURCE.SET_PLAN
        - RESOURCE.SET_LIMITS
        - RESOURCE.SET_BACKEND_ID
        - RESOURCE.ACCEPT_BOOKING_REQUEST
        - RESOURCE.REJECT_BOOKING_REQUEST
        - RESOURCE.SUBMIT_REPORT
        - RESOURCE.LIST_USERS
        - RESOURCE.COMPLETE_DOWNSCALING
        - RESOURCE.TERMINATE
        - RESOURCE.LIST_IMPORTABLE
        - RESOURCE.CREATE_ROBOT_ACCOUNT
        - RESOURCE.UPDATE_ROBOT_ACCOUNT
        - RESOURCE.DELETE_ROBOT_ACCOUNT
        {{ if has "owners_can_manage_owners" .Values.waldur.features }}
        - CUSTOMER.CREATE_PERMISSION
        - CUSTOMER.UPDATE_PERMISSION
        - CUSTOMER.DELETE_PERMISSION
        {{ end }}
        - PROJECT.CREATE_PERMISSION
        - PROJECT.UPDATE_PERMISSION
        - PROJECT.DELETE_PERMISSION
        - OFFERING.CREATE_PERMISSION
        - OFFERING.UPDATE_PERMISSION
        - OFFERING.DELETE_PERMISSION
        - PROJECT.CREATE
        - PROJECT.UPDATE
        - PROJECT.DELETE

    - role: CUSTOMER.MANAGER
      permissions:
        - RESOURCE.SET_END_DATE
        - RESOURCE.SET_BACKEND_ID
        - RESOURCE.ACCEPT_BOOKING_REQUEST
        - RESOURCE.REJECT_BOOKING_REQUEST
        - RESOURCE.SUBMIT_REPORT
        - RESOURCE.LIST_USERS
        - RESOURCE.COMPLETE_DOWNSCALING
        - RESOURCE.CREATE_ROBOT_ACCOUNT
        - RESOURCE.UPDATE_ROBOT_ACCOUNT
        - RESOURCE.DELETE_ROBOT_ACCOUNT
        - OFFERING.UPDATE_THUMBNAIL
        - OFFERING.UPDATE_ATTRIBUTES
        - OFFERING.UPDATE_LOCATION
        - OFFERING.UPDATE_DESCRIPTION
        - OFFERING.UPDATE_OVERVIEW
        - OFFERING.UPDATE_OPTIONS
        - OFFERING.UPDATE_SECRET_OPTIONS
        - OFFERING.ADD_ENDPOINT
        - OFFERING.DELETE_ENDPOINT
        - OFFERING.UPDATE_COMPONENTS
        - OFFERING.PAUSE
        - OFFERING.UNPAUSE
        - OFFERING.ARCHIVE
        - OFFERING.DRY_RUN_SCRIPT
        - OFFERING.MANAGE_CAMPAIGN
        - OFFERING.MANAGE_USER_GROUP

    - role: PROJECT.ADMIN
      {{ if has "academic_domain" .Values.waldur.features }}
      description: member
      {{ end }}
      {{ if has "academic_shared_domain" .Values.waldur.features }}
      description: co-PI
      {{ end }}
      permissions:
        {{ if has "admin_can_approve_order" .Values.waldur.features }}
        - ORDER.APPROVE
        {{ end }}
        - ORDER.APPROVE_PRIVATE
        - ORDER_ITEM.DESTROY
        - ORDER_ITEM.TERMINATE
        - RESOURCE.TERMINATE
        - RESOURCE.LIST_IMPORTABLE
        - RESOURCE.SET_PLAN
        - RESOURCE.SET_LIMITS

    - role: PROJECT.MANAGER
      {{ if has "academic_domain" .Values.waldur.features }}
      description: co-PI
      {{ end }}
      {{ if has "academic_shared_domain" .Values.waldur.features }}
      description: PI
      {{ end }}
      permissions:
        {{ if has "manager_can_approve_order" .Values.waldur.features }}
        - ORDER.APPROVE
        {{ end }}
        - ORDER.APPROVE_PRIVATE
        - ORDER_ITEM.DESTROY
        - ORDER_ITEM.TERMINATE
        - RESOURCE.TERMINATE
        - RESOURCE.LIST_IMPORTABLE
        - RESOURCE.SET_PLAN
        - RESOURCE.SET_LIMITS
        - PROJECT.CREATE_PERMISSION
        - PROJECT.UPDATE_PERMISSION
        - PROJECT.DELETE_PERMISSION
        - PROJECT.UPDATE

    - role: PROJECT.MEMBER
      {{ if has "enable_project_member_role" .Values.waldur.features }}
      is_active: true
      {{ else }}
      is_active: false
      {{ end }}
      {{ if has "academic_domain" .Values.waldur.features }}
      description: guest
      {{ end }}
      {{ if has "academic_shared_domain" .Values.waldur.features }}
      description: member
      {{ end }}
      permissions: []

    - role: OFFERING.MANAGER
      permissions:
        - OFFERING.UPDATE
        - OFFERING.UPDATE_ATTRIBUTES
        - OFFERING.UPDATE_LOCATION
        - OFFERING.UPDATE_DESCRIPTION
        - OFFERING.UPDATE_OVERVIEW
        - OFFERING.UPDATE_OPTIONS
        - OFFERING.UPDATE_SECRET_OPTIONS
        - OFFERING.ADD_ENDPOINT
        - OFFERING.DELETE_ENDPOINT
        - OFFERING.UPDATE_COMPONENTS
        - OFFERING.PAUSE
        - OFFERING.UNPAUSE
        - OFFERING.ARCHIVE
        - OFFERING.DRY_RUN_SCRIPT
        - RESOURCE.SET_USAGE
        - RESOURCE.SET_BACKEND_ID
        - RESOURCE.ACCEPT_BOOKING_REQUEST
        - RESOURCE.REJECT_BOOKING_REQUEST
