apiVersion: v1
kind: ConfigMap
metadata:
  name: api-uwsgi-config
data:
  uwsgi.ini: |-
    #
    # Waldur uWSGI configuration file
    #
    # See also: http://uwsgi-docs.readthedocs.io/en/latest/Configuration.html#ini-files

    [uwsgi]
    buffer-size = 8192
    enable-metrics = true
    gid = waldur
    logto = /var/log/waldur/uwsgi.log
    module = waldur_core.server.wsgi:application
    {{ if .Values.waldur.uwsgi.plugins }}
    plugins = {{ .Values.waldur.uwsgi.plugins }}
    {{ else }}
    plugins = python36
    {{ end }}
    {{ if .Values.waldur.uwsgi.processes }}
    processes = {{ .Values.waldur.uwsgi.processes }}
    {{ else }}
    processes = 16
    {{ end }}
    socket = :8000  # avoid localhost to fix binding issue
    static-map = /static=/usr/share/waldur/static
    static-map = /media=/var/lib/waldur/media
    {{ if .Values.waldur.uwsgi.statsPush }}
    stats-push = {{ .Values.waldur.uwsgi.statsPush }}
    {{ end }}
    uid = waldur
    enable-threads = true  # required by sentry-sdk

    http-socket = :8080
    http-enable-proxy-protocol = 1
    http-auto-chunked = true
    http-keepalive = 75
    http-timeout = 75
    offload-threads = $(UWSGI_OFFLOAD_THREADS)

    add-header = Access-Control-Allow-Credentials: true
    add-header = Access-Control-Allow-Headers: Accept, Accept-Encoding, Authorization, Content-Type, Origin, User-Agent, X-CSRFToken, X-Requested-With
    add-header = Access-Control-Allow-Methods: DELETE, GET, OPTIONS, PATCH, POST, PUT
    add-header = Access-Control-Allow-Origin: *
    add-header = Access-Control-Expose-Headers Link: X-Result-Count
    add-header = Connection: Keep-Alive
