apiVersion: v1
kind: ConfigMap
metadata:
  name: homeport-json-config
data:
  config.json: |
    {
      {{ if .Values.waldur.defaultLanguage }}
      "defaultLanguage": {{ .Values.waldur.defaultLanguage | quote }},
      {{ end }}
      
      {{ if .Values.waldur.languageChoices }}
      "languageChoices": [
      {{ if has "et" .Values.waldur.languageChoices }}
          { "code": "et", "label": "Estonian" },
      {{ end }}
      {{ if has "lv" .Values.waldur.languageChoices }}
          { "code": "lv", "label": "Latvian" },
      {{ end }}
      {{ if has "ru" .Values.waldur.languageChoices }}
          { "code": "ru", "label": "Russian" },
      {{ end }}
      {{ if has "it" .Values.waldur.languageChoices }}
          { "code": "it", "label": "Italian" },
      {{ end }}
      {{ if has "de" .Values.waldur.languageChoices }}
          { "code": "de", "label": "German" },
      {{ end }}
      {{ if has "es" .Values.waldur.languageChoices }}
          { "code": "es", "label": "Spanish" },
      {{ end }}
      {{ if has "ita" .Values.waldur.languageChoices }}
          { "code": "ita", "display_code": "en", "label": "English" }
      {{ else if has "neic" .Values.waldur.languageChoices }}
          { "code": "neic", "display_code": "en", "label": "English" }
      {{ else if has "par" .Values.waldur.languageChoices }}
          { "code": "par", "display_code": "en", "label": "English" }
      {{ else }}
          { "code": "en", "label": "English" }
      {{ end }}
      ],
      {{ end }}
      
      {{ if .Values.waldur.whitelabeling.shortPageTitle }}
      "shortPageTitle": {{ .Values.waldur.whitelabeling.shortPageTitle | quote }},
      {{ end }}

      {{ if .Values.waldur.whitelabeling.loginLogoUrl }}
      "loginLogo": {{ .Values.waldur.whitelabeling.loginLogoUrl | quote }},
      {{ else if .Values.waldur.whitelabeling.loginLogoPath }}
      "loginLogo": "images/login_logo.png",
      {{ end }}

      {{ if .Values.waldur.whitelabeling.sidebarLogoUrl }}
      "sidebarLogo": {{ .Values.waldur.whitelabeling.sidebarLogoUrl | quote }},
      {{ else if .Values.waldur.whitelabeling.sidebarLogoPath }}
      "sidebarLogo": "images/sidebar_logo.png",
      {{ end }}

      {{ if .Values.waldur.whitelabeling.poweredByLogoUrl }}
      "poweredByLogo": {{ .Values.waldur.whitelabeling.poweredByLogoUrl | quote}},
      {{ else if .Values.waldur.whitelabeling.poweredByLogoPath }}
      "poweredByLogo": "images/poweredby_logo.png",
      {{ end }}

      "apiEndpoint": {{ .Values.waldur.apiUrl | quote}}
    }
