apiVersion: v1
kind: ConfigMap
metadata:
  name: mastermind-template-config
data:
{{ $templatesPathPattern := .Values.waldur.mastermindTemplating.mastermindTemplatesPath | printf "%s/**" }}
{{ range $path, $data :=  .Files.Glob $templatesPathPattern }}
  {{ $path | base }}: |-
{{ $data | toString | indent 4 }}
{{ end }}
