apiVersion: v1
kind: ConfigMap
metadata:
  name: homeport-json-config
data:
  config.json: |
    {
      {{ if has "billing" .Values.waldur.features }}
      "accountingMode": "billing",
      {{ end }}

      {{ if has "secure_session" .Values.waldur.features }}
      "authStorage": "sessionStorage",
      {{ end }}

      {{ if .Values.waldur.sentryDSN }}
      "SENTRY_DSN": {{ .Values.waldur.sentryDSN | quote }},
      {{ end }}

      {{ if .Values.waldur.whitelabeling.loginLogoUrl }}
      "loginLogo": {{ .Values.waldur.whitelabeling.loginLogoUrl | quote }},
      {{ else if .Values.waldur.whitelabeling.loginLogoPath }}
      "loginLogo": "images/login_logo.png",
      {{ end }}

      {{ if .Values.waldur.whitelabeling.sidebarLogoUrl }}
      "sidebarLogo": {{ .Values.waldur.whitelabeling.sidebarLogoUrl | quote }},
      {{ else if .Values.waldur.whitelabeling.sidebarLogoPath }}
      "sidebarLogo": "images/sidebar_logo.png",
      {{ end }}

      {{ if .Values.waldur.whitelabeling.poweredByLogoUrl }}
      "poweredByLogo": {{ .Values.waldur.whitelabeling.poweredByLogoUrl | quote }},
      {{ else if .Values.waldur.whitelabeling.poweredByLogoPath }}
      "poweredByLogo": "images/poweredby_logo.png",
      {{ end }}

      "apiEndpoint": {{ printf "%s://%s/" .Values.apiScheme .Values.apiHostname | quote }}
    }
