{{ if .Values.waldur.notifications }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mastermind-notifications-config
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
data:
  notifications.json: |
{{ toJson .Values.waldur.notifications | indent 4 }}
{{ end }}
