apiVersion: v1
kind: ConfigMap
metadata:
  name: homeport-json-config
data:
  config.json: |
    {
      {{ if has "billing" .Values.waldur.features }}
      "accountingMode": "billing",
      {{ end }}

      {{ if has "secure_session" .Values.waldur.features }}
      "authStorage": "sessionStorage",
      {{ end }}

      "apiEndpoint": {{ printf "%s://%s/" .Values.apiScheme .Values.apiHostname | quote }}
    }
