{{ if .Values.postgresBackup.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: waldur-db-backup-cronjob
spec:
  schedule: {{ .Values.postgresBackup.schedule | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: "postgres-backup-cronjob"
              image: {{ .Values.global.imageRegistry }}/{{ .Values.postgresBackup.image }}
              command: ["/bin/sh"]
              args: ["-c", "backup"]
              env:
                - name: PGHOST
                  value: {{ template "waldur.postgresql.host" . }}
                - name: PGPORT
                  value: {{ template "waldur.postgresql.port" . }}
                - name: PGUSER
                  value: {{ template "waldur.postgresql.user" . }}
                - name: PGDATABASE
                  value: {{ template "waldur.postgresql.dbname" . }}
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ template "waldur.postgresql.secret" . }}
                      key: {{ template "waldur.postgresql.secret.passwordKey" . }}
                - name: MINIO_SERVER
                  value: {{ .Values.minio.endpoint | quote }}
                - name: MINIO_ACCESS_KEY
                  value: {{ .Values.minio.accessKey | quote }}
                - name: MINIO_SECRET_KEY
                  value: {{ .Values.minio.secretKey | quote }}
                - name: MINIO_BUCKET
                  value: {{ .Values.minio.bucketName | quote }}
                - name: MINIO_API_VERSION
                  value: "S3v4"
              volumeMounts:
                - name: postgres-backup-script
                  mountPath: /usr/local/bin/backup
                  subPath: backup
          volumes:
            - name: postgres-backup-script
              configMap:
                name: waldur-db-backup-script
                defaultMode: 0777
          restartPolicy: Never
{{ end }}
