apiVersion: apps/v1
kind: Deployment
metadata:
  name: waldur-homeport
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: waldur-homeport
  template:
    metadata:
      labels:
        app: waldur-homeport
    spec:
      containers:
        - name: waldur-homeport
          image: opennode/waldur-homeport:{{ .Values.waldur.imageTag }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: json
              mountPath: /opnd/config.json
              subPath: config.json
            - name: nginx
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            {{ if .Values.waldur.whitelabeling.tosHtmlPath }}
            - name: tos
              mountPath: /var/www/waldur/tos.html
              subPath: tos.html
            {{ end }}
            {{ if .Values.waldur.whitelabeling.manifestJsonPath }}
            - name: manifest
              mountPath: /var/www/waldur/manifest.json
              subPath: manifest.json
            {{ end }}
            {{ if .Values.waldur.whitelabeling.privacyHtmlPath }}
            - name: privacy
              mountPath: /var/www/waldur/privacy.html
              subPath: privacy.html
            {{ end }}
            {{ if or .Values.waldur.whitelabeling.logo96Path .Values.waldur.whitelabeling.logo96BlobPath }}
            - name: logo96
              mountPath: /var/www/waldur/logo-96x96.png
              subPath: logo-96x96.png
            {{ end }}
            {{ if or .Values.waldur.whitelabeling.logo144Path .Values.waldur.whitelabeling.logo144BlobPath }}
            - name: logo144
              mountPath: /var/www/waldur/logo-144x144.png
              subPath: logo-144x144.png
            {{ end }}
            {{ if or .Values.waldur.whitelabeling.logo192Path .Values.waldur.whitelabeling.logo192BlobPath }}
            - name: logo192
              mountPath: /var/www/waldur/logo-192x192.png
              subPath: logo-192x192.png
            {{ end }}
            {{ if or .Values.waldur.whitelabeling.faviconPath .Values.waldur.whitelabeling.faviconBlobPath }}
            - name: favicon
              mountPath: /var/www/waldur/favicon.ico
              subPath: favicon.ico
            {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: json
        configMap:
          name: homeport-json-config
      - name: nginx
        configMap:
          name: homeport-nginx-config
      {{ if .Values.waldur.whitelabeling.tosHtmlPath }}
      - name: tos
        configMap:
          name: homeport-tos-config
      {{ end }}
      {{ if .Values.waldur.whitelabeling.manifestJsonPath }}
      - name: manifest
        configMap:
          name: homeport-manifest-config
      {{ end }}
      {{ if .Values.waldur.whitelabeling.privacyHtmlPath }}
      - name: privacy
        configMap: 
          name: homeport-privacy-config
      {{ end }}
      {{ if or .Values.waldur.whitelabeling.logo96Path .Values.waldur.whitelabeling.logo96BlobPath }}    
      - name: logo96
        configMap: 
          name: homeport-logo96-config
      {{ end }}
      {{ if or .Values.waldur.whitelabeling.logo144Path .Values.waldur.whitelabeling.logo144BlobPath }}
      - name: logo144
        configMap:
          name: homeport-logo144-config
      {{ end }}
      {{ if or .Values.waldur.whitelabeling.logo192Path .Values.waldur.whitelabeling.logo192BlobPath }}
      - name: logo192
        configMap:
          name: homeport-logo192-config
      {{ end }}
      {{ if or .Values.waldur.whitelabeling.faviconPath .Values.waldur.whitelabeling.faviconBlobPath }}
      - name: favicon
        configMap:
          name: homeport-favicon-config
      {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
