apiVersion: apps/v1
kind: Deployment
metadata:
  name: waldur-homeport
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: waldur-homeport
  template:
    metadata:
      labels:
        app: waldur-homeport
    spec:
      {{ if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range $i, $val := .Values.imagePullSecrets }}
        - name: {{ $val }}
        {{ end -}}
      {{ end }}
      {{ if .Values.hostAliases }}
      hostAliases:
        {{ toYaml .Values.hostaliases | nindent 8 }}
      {{ end }}
      containers:
        - name: waldur-homeport
          image: {{ .Values.global.imageRegistry }}/{{ .Values.waldur.homeport.imageName }}:{{ .Values.waldur.imageTag }}
          imagePullPolicy: {{ .Values.waldur.pullPolicy }}
          livenessProbe:
            httpGet:
              port: 80
              path: /scripts/configs/config.json
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              port: 80
              path: /scripts/configs/config.json
            initialDelaySeconds: 3
            periodSeconds: 3
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: TITLE
              value: {{ .Values.waldur.whitelabeling.shortPageTitle }}
          volumeMounts:
            - name: json
              mountPath: /opnd/config.json
              subPath: config.json
            - name: nginx
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: icons
              mountPath: /var/www/waldur/icons
          resources:
            {{- toYaml .Values.homeportResources | nindent 12 }}
      volumes:
      - name: json
        configMap:
          name: homeport-json-config
      - name: nginx
        configMap:
          name: homeport-nginx-config
      - name: icons
        configMap:
          name: homeport-icons-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
