{{ if .Values.waldur.metricsExporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waldur-metrics-exporter
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: waldur-metrics-exporter
  template:
    metadata:
      labels:
        app: waldur-metrics-exporter
        prometheus.io/scrape: 'true'
        prometheus.io/scrape-path: '/metrics'
        prometheus.io/scrape-port: '8080'
    spec:
      {{ if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range $i, $val := .Values.imagePullSecrets }}
        - name: {{ $val }}
        {{ end -}}
      {{ end }}
      containers:
      - name: waldur-metrics-exporter
        image: {{ .Values.global.imageRegistry }}/opennode/waldur-prometheus-exporter:latest
        imagePullPolicy: {{ .Values.waldur.pullPolicy }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        env:
          - name: WALDUR_API_URL
            value: {{ printf "%s://%s/api/" .Values.apiScheme .Values.apiHostname | quote }}
          - name: WALDUR_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: waldur-secret
                key: WALDUR_SUPPORT_API_TOKEN
        {{- with .Values.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
{{ end }}
