apiVersion: apps/v1
kind: Deployment
metadata:
  name: waldur-mastermind-beat
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: waldur-mastermind-beat
  template:
    metadata:
      labels:
        app: waldur-mastermind-beat
    spec:
      containers:
        - name: waldur-mastermind-beat
          image: {{ .Values.global.imageRegistry }}/{{ .Values.waldur.imageName }}:{{ .Values.waldur.imageTag }}
          imagePullPolicy: {{ .Values.waldur.pullPolicy }}
          args:
            - "beat"
          env:
          - name: GLOBAL_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: waldur-secret
                key: GLOBAL_SECRET_KEY
          - name: POSTGRESQL_HOST
            value: {{ template "waldur.postgresql.host" . }}
          - name: POSTGRESQL_PORT
            value: {{ template "waldur.postgresql.port" . }}
          - name: POSTGRESQL_USER
            value: {{ template "waldur.postgresql.user" . }}
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "waldur.postgresql.secret" . }}
                key: {{ template "waldur.postgresql.secret.passwordKey" . }}
          - name: POSTGRESQL_NAME
            value: {{ template "waldur.postgresql.dbname" . }}
          {{ if .Values.waldur.sentryDSN }}
          - name: SENTRY_DSN
            value: {{ .Values.waldur.sentryDSN | quote }}
          {{ end }}
          {{ if .Values.waldur.disabledExtensions }}
          - name: WALDUR_DISABLED_EXTENSIONS
            value: {{ .Values.waldur.disabledExtensions | toJson | quote }}
          {{ end }}
          resources:
            {{ if .Values.hpa.celery.enabled }}
            {{- toYaml .Values.hpa.celery.beatResources | nindent 12 }}
            {{ else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{ end }}
          volumeMounts:
            - name: api-override
              mountPath: /etc/waldur/override.conf.py
              subPath: override.conf.py
            - name: api-celery
              mountPath: /etc/waldur/celery.conf
              subPath: celery.conf
            - name: logging-override
              mountPath: /etc/waldur/logging.conf.py
              subPath: logging.conf.py
            - name: logging-override
              mountPath: /usr/local/bin/beat
              subPath: beat
            {{ if .Values.waldur.ssh_public_key_path }}
            - name: waldur-ssh-pub-key
              mountPath: /etc/waldur/id_rsa.pub
              subPath: id_rsa.pub
            {{ end }}
            {{ if .Values.waldur.ssh_private_key_path }}
            - name: waldur-ssh-key
              mountPath: /etc/waldur/id_rsa
              subPath: id_rsa
            {{ end }}
        {{ if .Values.logManagement.enabled }}
            - name: waldur-log
              mountPath: /var/log/waldur
        - name: fluentd
          image: {{ .Values.global.imageRegistry }}/{{ .Values.logManagement.fluentImageName }}:{{ .Values.logManagement.fluentImageTag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: {{ .Values.logManagement.elasticHost | quote }}
            - name: FLUENT_ELASTICSEARCH_PORT
              value: {{ .Values.logManagement.elasticPort | quote }}
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: {{ .Values.logManagement.elasticProtocol | quote }}
            - name: FLUENT_INDEX_NAME
              value: {{ .Values.logManagement.fluentIndexName | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: waldur-log
              mountPath: /var/log/waldur
            - name: fluentd-conf
              mountPath: /fluentd/etc
        {{ end }}
      volumes:
      - name: api-override
        configMap:
          name: api-override-config
      - name: api-celery
        configMap:
          name: api-celery-config
      - name: logging-override
        configMap:
          name: mastermind-logging-override-config
          items:
            - key: beat
              path: beat
              mode: 0755
            - key: logging.conf.py
              path: logging.conf.py
      {{ if .Values.logManagement.enabled }}
      - name: waldur-log
        emptyDir: {}
      - name: fluentd-conf
        configMap:
          name: fluentd-config
      {{ end }}
      {{ if .Values.waldur.ssh_public_key_path }}
      - name: waldur-ssh-pub-key
        configMap:
          name: waldur-ssh-pub-key-config
      {{ end }}
      {{ if .Values.waldur.ssh_private_key_path }}
      - name: waldur-ssh-key
        secret:
          secretName: waldur-ssh-key-config
          defaultMode: 0600
      {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
