apiVersion: apps/v1
kind: Deployment
metadata:
  name: waldur-mastermind-worker
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  {{ if .Values.extraReplicas.celery }}
  replicas: {{ add .Values.replicaCount .Values.extraReplicas.celery }}
  {{ else }}
  replicas: {{ .Values.replicaCount }}
  {{ end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "waldur.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "waldur.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: waldur-mastermind-worker
          image: opennode/waldur-mastermind:{{ .Values.waldur.imageTag }}
          args:
            - "worker"
          livenessProbe:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "celery inspect -q -A waldur_core.server -d celery@$HOSTNAME ping"
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "celery inspect -q -A waldur_core.server -d celery@$HOSTNAME ping"
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 10
          env:
          - name: GLOBAL_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: waldur-secret
                key: GLOBAL_SECRET_KEY
          - name: POSTGRESQL_HOST
            value: {{ .Values.postgresql.postgresqlHost }}
          - name: POSTGRESQL_PORT
            value: {{ .Values.postgresql.postgresqlPort | quote }}
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ template "waldur.postgresql.secret" . }}
                key: POSTGRES_USER
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "waldur.postgresql.secret" . }}
                key: POSTGRES_PASSWORD
          - name: POSTGRESQL_NAME
            value: {{ .Values.postgresql.postgresqlDatabase | quote }}
          - name: REDIS_HOST
            value: {{ template "waldur.redis.host" . }}
          - name: REDIS_PORT
            value: {{ template "waldur.redis.port" . }}
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
              {{- if .Values.redis.existingSecret }}
                name: {{ .Values.redis.existingSecret }}
              {{- else }}
                name: {{ template "waldur.redis.secret" . }}
              {{- end }}
                key: {{ template "waldur.redis.secretKey" . }}
          resources:
            {{ if .Values.hpa.celery.enabled }}
            {{- toYaml .Values.hpa.celery.workerResources | nindent 12 }}
            {{ else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{ end }}
          volumeMounts:
            - name: api-core
              mountPath: /etc/waldur/core.ini
              subPath: core.ini
            - name: api-override
              mountPath: /etc/waldur/override.conf.py
              subPath: override.conf.py
            - name: api-celery
              mountPath: /etc/waldur/celery.conf
              subPath: celery.conf
            - name: api-uwsgi
              mountPath: /etc/waldur/uwsgi.ini
              subPath: uwsgi.ini
        {{ if .Values.logManagement.enabled }}
            - name: waldur-log
              mountPath: /var/log/waldur
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.11.0-debian-elasticsearch7-1.0
          imagePullPolicy: IfNotPresent
          env:
            - name:  FLUENT_ELASTICSEARCH_HOST
              value: {{ .Values.logManagement.elasticHost | quote }}
            - name:  FLUENT_ELASTICSEARCH_PORT
              value: {{ .Values.logManagement.elasticPort | quote }}
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: {{ .Values.logManagement.elasticProtocol | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: waldur-log
              mountPath: /var/log/waldur
            - name: fluentd-conf
              mountPath: /fluentd/etc
        {{ end }}
      volumes:
      - name: api-core
        configMap:
          name: api-core-config
      - name: api-override
        configMap:
          name: api-override-config
      - name: api-celery
        configMap:
          name: api-celery-config
      - name: api-uwsgi
        configMap:
          name: api-uwsgi-config
      {{ if .Values.logManagement.enabled }}
      - name: waldur-log
        emptyDir: {}
      - name: fluentd-conf
        configMap:
          name: fluentd-config
      {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
