{{ if .Values.eosc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waldur-eosc-order-processor
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: eosc-order-processor
  template:
    metadata:
      labels:
        app: eosc-order-processor
    spec:
      {{ if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range $i, $val := .Values.imagePullSecrets }}
        - name: {{ $val }}
        {{ end -}}
      {{ end }}
      containers:
        - name: waldur-eosc-order-processor
          image: {{ .Values.global.imageRegistry }}/opennode/waldur-eosc-order-processor:latest
          imagePullPolicy: {{ .Values.waldur.pullPolicy }}
          # TODO
          # livenessProbe:
          # readinessProbe:
          env:
          - name: EOSC_URL
            value: {{ .Values.eosc.eoscUrl | quote }}
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: waldur-eosc-secret
                key: orderToken
          - name: WALDUR_TARGET_ORGANIZATION_NAME
            value: {{ .Values.eosc.waldurTargetOrgName | quote }}
          - name: OMS_ID
            value: {{ .Values.eosc.omsID | quote }}
          - name: WALDUR_URL
            value: http://waldur-mastermind-api:8080/api/
          - name: WALDUR_TOKEN
            valueFrom:
              secretKeyRef:
                name: waldur-eosc-secret
                key: waldurToken
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
{{ end }}
