{{ if .Values.postgresBackup.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waldur-db-restore
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  replicas: {{ default 1 .Values.replicaCount | int }}
  selector:
    matchLabels:
      app: waldur-db-restore
  template:
    metadata:
      labels:
        app: waldur-db-restore
    spec:
      {{ if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range $i, $val := .Values.imagePullSecrets }}
        - name: {{ $val }}
        {{ end -}}
      {{ end }}
      {{ if .Values.hostAliases }}
      hostAliases:
        {{ toYaml .Values.hostaliases | nindent 8 }}
      {{ end }}
      containers:
        - name: "waldur-postgres-restore"
          image: {{ .Values.global.imageRegistry }}/{{ .Values.postgresBackup.image }}
          imagePullPolicy: {{ .Values.waldur.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "while true; do sleep 100; done;"]
          env:
            - name: PGHOST
              value: {{ template "waldur.postgresql.host" . }}
            - name: PGPORT
              value: {{ template "waldur.postgresql.port" . }}
            - name: PGUSER
              value: {{ template "waldur.postgresql.user" . }}
            - name: PGDATABASE
              value: {{ template "waldur.postgresql.dbname" . }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "waldur.postgresql.secret" . }}
                  key: {{ template "waldur.postgresql.secret.passwordKey" . }}
            - name: MINIO_SERVER
              value: {{ .Values.minio.endpoint | quote }}
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.minio.accessKey | quote }}
            - name: MINIO_SECRET_KEY
              value: {{ .Values.minio.secretKey | quote }}
            - name: MINIO_BUCKET
              value: {{ .Values.minio.bucketName | quote }}
            - name: MINIO_API_VERSION
              value: "S3v4"
          volumeMounts:
            - name: waldur-db-backup-minio-auth
              mountPath: /usr/local/bin/db-backup-minio-auth
              subPath: minio-auth
      volumes:
        - name: waldur-db-backup-minio-auth
          configMap:
            name: waldur-db-backup-minio-auth
            defaultMode: 0755

{{ end }}
