apiVersion: apps/v1
kind: Deployment
metadata:
  name: waldur-mastermind-api
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  {{ if .Values.extraReplicas.api }}
  replicas: {{ add .Values.replicaCount .Values.extraReplicas.api }}
  {{ else }}
  replicas: {{ .Values.replicaCount }}
  {{ end }}
  selector:
    matchLabels:
      app: waldur-mastermind-api
  template:
    metadata:
      labels:
        app: waldur-mastermind-api
    spec:
      {{ if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range $i, $val := .Values.imagePullSecrets }}
        - name: {{ $val }}
        {{ end -}}
      {{ end }}
      {{ if .Values.hostAliases }}
      hostAliases:
        {{ toYaml .Values.hostaliases | nindent 8 }}
      {{ end }}
      containers:
        - name: waldur-mastermind-api
          image: {{ .Values.global.imageRegistry }}/{{ .Values.waldur.imageName }}:{{ .Values.waldur.imageTag }}
          imagePullPolicy: {{ .Values.waldur.pullPolicy }}
          args:
            - "mastermind"
          livenessProbe:
            httpGet:
              port: 8080
              path: /api/configuration/
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 100
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/configuration/
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 100
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: GLOBAL_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: waldur-secret
                key: GLOBAL_SECRET_KEY
          - name: POSTGRESQL_HOST
            value: {{ template "waldur.postgresql.host" . }}
          - name: POSTGRESQL_PORT
            value: {{ template "waldur.postgresql.port" . }}
          - name: POSTGRESQL_USER
            value: {{ template "waldur.postgresql.user" . }}
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "waldur.postgresql.secret" . }}
                key: {{ template "waldur.postgresql.secret.passwordKey" . }}
          - name: POSTGRESQL_NAME
            value: {{ template "waldur.postgresql.dbname" . }}
          {{ if .Values.waldur.sentryDSN }}
          - name: SENTRY_DSN
            value: {{ .Values.waldur.sentryDSN | quote }}
          - name: SENTRY_ENVIRONMENT
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{ end }}
          {{ if .Values.waldur.disabledExtensions }}
          - name: WALDUR_DISABLED_EXTENSIONS
            value: {{ .Values.waldur.disabledExtensions | toJson | quote }}
          {{ end }}
          {{ if .Values.proxy.httpsProxy }}
          - name: https_proxy
            value: {{ .Values.proxy.httpsProxy | quote }}
          {{ end }}
          {{ if .Values.proxy.httpProxy }}
          - name: http_proxy
            value: {{ .Values.proxy.httpProxy | quote }}
          {{ end }}
          {{ if .Values.proxy.noProxy }}
          - name: no_proxy
            value: {{ .Values.proxy.noProxy | quote }}
          {{ end }}
          resources:
            {{ if .Values.hpa.api.enabled }}
            {{- toYaml .Values.hpa.api.resources | nindent 12 }}
            {{ else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{ end }}
          volumeMounts:
            - name: api-override
              mountPath: /etc/waldur/override.conf.py
              subPath: override.conf.py
            - name: api-celery
              mountPath: /etc/waldur/celery.conf
              subPath: celery.conf
            {{ if has "SAML2" .Values.waldur.authMethods }}
            - name: waldur-saml2-certs
              mountPath: /etc/waldur/saml2/credentials
            - name: waldur-saml2-conf
              mountPath: /etc/waldur/saml2.conf.py
              subPath: saml2.conf.py
            {{ end }}
            {{ if has "VALIMO" .Values.waldur.authMethods }}
            - name: waldur-valimo-certs
              mountPath: /etc/waldur/valimo
            {{ end }}
            {{ if .Values.waldur.ssh_public_key_path }}
            - name: waldur-ssh-pub-key
              mountPath: /etc/waldur/id_rsa.pub
              subPath: id_rsa.pub
            {{ end }}
            {{ if .Values.waldur.ssh_private_key_path }}
            - name: waldur-ssh-key
              mountPath: /etc/waldur/id_rsa
              subPath: id_rsa
            {{ end }}
            {{ if .Values.waldur.marketplace.script.enabled }}
            - name: waldur-script-kubeconfig
              mountPath: /etc/waldur/kubeconfig
              subPath: kubeconfig
              readOnly: true
            {{ end }}
      volumes:
      - name: api-override
        configMap:
          name: api-override-config
      - name: api-celery
        configMap:
          name: api-celery-config
      {{ if has "SAML2" .Values.waldur.authMethods }}
      - name: waldur-saml2-certs
        secret:
          secretName: waldur-saml2-secret
      - name: waldur-saml2-conf
        configMap:
          name: waldur-saml2-conf-config
      {{ end }}
      {{ if has "VALIMO" .Values.waldur.authMethods }}
      - name: waldur-valimo-certs
        secret:
          secretName: waldur-valimo-secret
      {{ end }}
      {{ if .Values.waldur.ssh_public_key_path }}
      - name: waldur-ssh-pub-key
        configMap:
          name: waldur-ssh-pub-key-config
      {{ end }}
      {{ if .Values.waldur.ssh_private_key_path }}
      - name: waldur-ssh-key
        secret:
          secretName: waldur-ssh-key-config
          defaultMode: 0600
      {{ end }}
      {{ if .Values.waldur.marketplace.script.enabled }}
      - name: waldur-script-kubeconfig
        secret:
          secretName: waldur-script-kubeconfig
      {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
