apiVersion: apps/v1
kind: Deployment
metadata:
  name: waldur-mastermind-api
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: waldur-mastermind-api
  template:
    metadata:
      labels:
        app: waldur-mastermind-api
    spec:
      containers:
        - name: waldur-mastermind-api
          image: nginx:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: api-nginx
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          {{- if .Values.persistence.enabled }}
            - name: media
              mountPath: /var/lib/waldur/
              subPath: {{ .Values.persistence.subPath | default "" }}
          {{- end }}
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: media
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "waldur.fullname" .) }}
      {{- end }}
      - name: api-nginx
        configMap:
          name: api-nginx-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

