{{- if or ( gt .Capabilities.KubeVersion.Major "1" ) ( ge .Capabilities.KubeVersion.Minor "19" ) }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: homeport-ingress
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{ if .Values.ingress.tls.source | eq "letsEncrypt" }}
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
    {{ end }}
spec:
  rules:
  - host: {{ .Values.homeportHostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: waldur-homeport
            port:
              number: 80
  tls:
  - hosts:
    - {{ .Values.homeportHostname }}
    secretName: homeport-certificate
