{{- if or ( gt .Capabilities.KubeVersion.Major "1" ) ( ge .Capabilities.KubeVersion.Minor "19" ) }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: api-ingress-admin
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,sentry-trace,baggage,X-Impersonated-User-Uuid
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{ if and .Values.ingress.tls.enabled (eq .Values.ingress.tls.source "letsEncrypt") }}
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
    {{ end }}
    {{ if .Values.ingress.whitelistSourceRangeAdmin }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ .Values.ingress.whitelistSourceRangeAdmin }}"
    {{ else if .Values.ingress.whitelistSourceRange }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ .Values.ingress.whitelistSourceRange }}"
    {{ end }}
spec:
  rules:
  - host: {{ .Values.apiHostname }}
    http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: waldur-mastermind-api
            port:
              number: 80
      - path: /static
        pathType: Prefix
        backend:
          service:
            name: waldur-mastermind-api
            port:
              number: 80
  {{ if .Values.apiExtraHosts }}
  {{- range .Values.apiExtraHosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: waldur-mastermind-api
            port:
              number: 80
      - path: /static
        pathType: Prefix
        backend:
          service:
            name: waldur-mastermind-api
            port:
              number: 80
  {{- end }}
  {{ end }}
  {{ if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.apiHostname }}
    {{ if .Values.apiExtraHosts }}
    {{- range .Values.apiExtraHosts }}
    - {{ . }}
    {{- end }}
    {{ end }}
    {{ if .Values.ingress.tls.customMastermindSecretName }}
    secretName: {{ .Values.ingress.tls.customMastermindSecretName | quote }}
    {{ else }}
    secretName: api-certificate
    {{ end }}
  {{ end }}
