apiVersion: batch/v1
kind: Job
metadata:
  name: waldur-mastermind-job
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  template:
    metadata:
      annotations:
        "helm.sh/hook": post-install, post-upgrade
        "helm.sh/hook-weight": "0"
        "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
    spec:
      containers:
        - name: waldur-mastermind-job
          image: opennode/waldur-mastermind:{{ $.Chart.AppVersion }}
          args:
            - "waldur"
            - "migrate"
            - "--noinput"
          env:
          - name: POSTGRESQL_USER
            value: "waldur"
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: waldur-secret
                key: POSTGRESQL_PASSWORD
          - name: GLOBAL_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: waldur-secret
                key: GLOBAL_SECRET_KEY
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      restartPolicy: "Never"
