apiVersion: batch/v1
kind: Job
metadata:
  name: waldur-mastermind-job
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  template:
    metadata:
      annotations:
        "helm.sh/hook": post-install, post-upgrade
        "helm.sh/hook-weight": "0"
        "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
    spec:
      containers:
        - name: waldur-mastermind-job
          image: opennode/waldur-mastermind:{{ $.Chart.AppVersion }}
          args:
            - initdb
          env:
          - name: POSTGRESQL_HOST
            value: {{ template "waldur.postgresql.host" . }}
          - name: POSTGRESQL_PORT
            value: {{ template "waldur.postgresql.port" . }}
          - name: POSTGRESQL_USER
            value: {{ default "waldur" .Values.postgresql.postgresqlUsername | quote }}
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: waldur-secret
                key: POSTGRESQL_PASSWORD
          - name: POSTGRESQL_NAME
            value: {{ default "waldur" .Values.postgresql.postgresqlDatabase | quote }}
          - name: REDIS_HOST
            value: {{ template "waldur.redis.host" . }}
          - name: REDIS_PORT
            value: {{ template "waldur.redis.port" . }}
          - name: GLOBAL_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: waldur-secret
                key: GLOBAL_SECRET_KEY
          volumeMounts:
            - name: api-core
              mountPath: /etc/waldur/core.ini
              subPath: core.ini
            - name: api-override
              mountPath: /etc/waldur/override.conf.py
              subPath: override.conf.py
            - name: api-celery
              mountPath: /etc/waldur/celery.conf
              subPath: celery.conf
            - name: api-uwsgi
              mountPath: /etc/waldur/uwsgi.ini
              subPath: uwsgi.ini
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: api-core
        configMap:
          name: api-core-config
      - name: api-override
        configMap:
          name: api-override-config
      - name: api-celery
        configMap:
          name: api-celery-config
      - name: api-uwsgi
        configMap:
          name: api-uwsgi-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      restartPolicy: "Never"
