apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.apiUrl }}
    http:
      paths:
      - path: /
        backend:
          serviceName: waldur-mastermind-api
          servicePort: 8080
