apiVersion: apps/v1
kind: Deployment
metadata:
  name: waldur-mastermind-uwsgi
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: waldur-mastermind-uwsgi
  template:
    metadata:
      labels:
        app: waldur-mastermind-uwsgi
    spec:
      containers:
        - name: waldur-mastermind-uwsgi
          image: opennode/waldur-mastermind:{{ $.Chart.AppVersion }}
          args:
            - "mastermind"
          ports:
            - name: uwsgi
              containerPort: 8000
              protocol: TCP
          env:
          - name: POSTGRESQL_USER
            value: "waldur"
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: waldur-secret
                key: POSTGRESQL_PASSWORD
          - name: GLOBAL_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: waldur-secret
                key: GLOBAL_SECRET_KEY
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: api-core
              mountPath: /etc/waldur/core.ini
              subPath: core.ini
            - name: api-override
              mountPath: /etc/waldur/override.conf.py
              subPath: override.conf.py
            - name: api-celery
              mountPath: /etc/waldur/celery.conf
              subPath: celery.conf
            - name: api-uwsgi
              mountPath: /etc/waldur/uwsgi.ini
              subPath: uwsgi.ini
      volumes:
      - name: api-core
        configMap:
          name: api-core-config
      - name: api-override
        configMap:
          name: api-override-config
      - name: api-celery
        configMap:
          name: api-celery-config
      - name: api-uwsgi
        configMap:
          name: api-uwsgi-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
