{{ if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: waldur-homeport-network-policy
spec:
  podSelector:
    matchLabels:
      app: waldur-homeport
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports: 
        - protocol: TCP
          port: 80 
  egress: []
{{ end }}
