{{ if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: waldur-mastermind-api-policy
spec:
  podSelector:
    matchLabels:
      app: waldur-mastermind-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
    ports: 
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
  egress:
  - to: [] 
{{ end }}
