apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: {{ template "waldur.postgresql.host" . }}
spec:
  teamId: {{ template "waldur.postgresql.team" . }}
  postgresql:
    version: {{ .Values.postgresql.version | quote }}
  numberOfInstances: {{ .Values.postgresql.replicaCount }}
  volume:
    size: {{ .Values.postgresql.size }}
    {{ if .Values.postgresql.storageClass }}
    storageClass: {{ .Values.postgresql.storageClass | quote }}
    {{ end }}
  users:
    {{ template "waldur.postgresql.user" . }}:
      - superuser
      - createdb
  databases:
    {{ template "waldur.postgresql.dbname" . }}: {{ template "waldur.postgresql.user" . }}
  enableMasterLoadBalancer: {{ .Values.postgresql.loadBalancing.enableMaster }}
  enableReplicaLoadBalancer: {{ .Values.postgresql.loadBalancing.enableReplica }}
  enableLogicalBackup: {{ .Values.postgresql.enableLogicalBackup }}
