apiVersion: v1
kind: Secret
metadata:
  name: waldur-secret
type: Opaque
data:
  POSTGRESQL_PASSWORD: {{ "waldur" | b64enc | quote }}
  GLOBAL_SECRET_KEY: {{ "x2pYXyrAOwzXA2QOPzygIgkKFVMj/lUbZryWWbHoMtY=" | b64enc | quote }} 
