{{ if .Values.waldur.marketplace.script.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: waldur-script-kubeconfig
type: Opaque
data:
  kubeconfig: |-
{{ if .Values.waldur.marketplace.script.kubeconfig }}
{{ .Values.waldur.marketplace.script.kubeconfig | b64enc | indent 4 }}
{{ else }}
{{ .Files.Get .Values.waldur.marketplace.script.kubeconfigPath | b64enc | indent 4 }}
{{ end }}

{{ end }}
