{{ if or .Values.waldur.ssh_private_key_path .Values.waldur.ssh_private_key }}
kind: Secret
apiVersion: v1
metadata:
  name: waldur-ssh-key-config
type: Opaque
data:
  id_rsa: |-
{{ if .Values.waldur.ssh_private_key }}
{{ .Values.waldur.ssh_private_key | b64enc | indent 4 }}
{{ else }}
{{ if .Values.waldur.ssh_public_key_path }}
{{ .Files.Get .Values.waldur.ssh_private_key_path | b64enc | indent 4 }}
{{ end }}
{{ end }}

{{ end }}
