apiVersion: v1
kind: Secret
metadata:
  name: {{ template "waldur.postgresql.secret" . }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
