apiVersion: v1
kind: Secret
metadata:
  name: waldur-secret
type: Opaque
data:
  GLOBAL_SECRET_KEY: {{ .Values.waldur.secretKey | b64enc | quote }}
{{ if .Values.waldur.metricsExporter.enabled }}
  WALDUR_SUPPORT_API_TOKEN: {{ .Values.waldur.supportToken | b64enc | quote }}
{{ end }}
