{{ if has "VALIMO" .Values.waldur.authMethods }}
apiVersion: v1
kind: Secret
metadata:
  name: waldur-valimo-secret
type: Opaque
data:
{{ if .Values.waldur.valimo.valimoClientCrt }}
  valimo-client.crt: |
{{ .Values.waldur.valimo.valimoClientCrt | b64enc | indent 4 }}
{{ else }}
{{ $certsDirTemp := .Values.waldur.valimo.dir | printf "%s/valimo-client.crt" }}
{{ (.Files.Glob $certsDirTemp).AsSecrets | indent 2 }}
{{ end }}

{{ if .Values.waldur.valimo.valimoClientKey }}
  valimo-client.key: |
{{ .Values.waldur.valimo.valimoClientKey | b64enc | indent 4 }}
{{ else }}
{{ $certsDirTemp := .Values.waldur.valimo.dir | printf "%s/valimo-client.key" }}
{{ (.Files.Glob $certsDirTemp).AsSecrets | indent 2 }}
{{ end }}

{{ end }}
