apiVersion: v1
kind: Service
metadata:
  name: waldur-mastermind-api
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: waldur-mastermind-api
