name: waldur
description: Waldur - Open-Source Cloud Marketplace
keywords:
  - marketplace
  - openstack
  - vmware
  - slurm
  - billing
home: https://waldur.com
maintainers:
  - name: OpenNode team
    email: info@opennodecloud.com
apiVersion: v1
appVersion: "1.0"
