dependencies:
  - name: redis
    version: 9.3.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: redis.enabled
  - name: minio
    version: 5.0.30
    repository: https://kubernetes-charts.storage.googleapis.com/
