# Default values for waldur.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

extraReplicas:
  celery:
  api:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

apiScheme: "http"
homeportScheme: "http"
apiHostname: waldur.local
homeportHostname: waldur.local

affinity: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

hpa:
  api:
    enabled: false
    resources:
      requests:
        cpu: 500m
    cpuUtilizationBorder: 70
  celery:
    enabled: false
    workerResources:
      requests:
        cpu: 2000m
    beatResources:
      requests:
        cpu: 300m
    cpuUtilizationBorder: 80

nodeSelector: {}

tolerations: []

service:
  type: ClusterIP
  port: 80

storageClassName: local-storage

ingress:
  tls:
    source: "letsEncrypt" # Possible values: `letsEncrypt` and `secret`
    secretsDir: "tls"  # Enabled only if source == `secret`
  whitelistSourceRange: '' # E.g. '192.168.22.0/24'

celery:
  worker:
    enabled: true

waldur:
  imageName: "opennode/waldur-mastermind"
  imageTag: "latest"
  initdbImageName: "bitnami/postgresql"
  pullPolicy: Always
  secretKey: "SecretKeyChangeMe"
  supportToken: ""
  staffToken: ""
  disabledExtensions: []
  mail:
    host: ""
    port: ""
    username: ""
    password: ""
    useTLS: "false"
    useSSL: "false"
    from: ""
    replyTo: ""
  notificationSubject: ""
  timeZone: "UTC"
  features: []
  currencyName: "EUR"
  mastermindUrl: ""
  site:
    name: "Waldur"
    logo: ""
    address: ""
    email: ""
    phone: ""
  defaultLanguage: "en"
  languageChoices:
    - en
    - et
    - de
    - es
    - ru
    - lv
    - it
  authMethods:
    - LOCAL_SIGNIN
  socialAuthMethods: []
  smartid:
    secret: ""
    clientId: ""
  tara:
    secret: ""
    clientId: ""
  keycloak:
    auth_url: ""
    client_id: ""
    label: "Keycloak"
    secret: ""
    token_url: ""
    userinfo_url: ""
  eduteams:
    label: "eduTEAMS"
    clientId: ""
    secret: ""
    authUrl: "https://proxy.acc.eduteams.org/saml2sp/OIDC/authorization"
    tokenUrl: "https://proxy.acc.eduteams.org/OIDC/token"
    userinfoUrl: "https://proxy.acc.eduteams.org/OIDC/userinfo"
    remoteRefreshToken: ""
    remoteClientID: ""
    remoteSecret: ""
    remoteUserinfoUrl: ""
    remoteTokenUrl: ""
    enableSync: false
  ldap:
    host: ""
    baseDN: ""
    userDN: ""
    user: ""
    password: ""
    admins: ""
    support: ""
  freeipa:
    hostname: ""
    password: ""
    username: ""
    verifySSL: ""
    groupnamePrefix: ""
    usernamePrefix: ""
  valimo:
    apId: ""
    apPwd: ""
    dnsname: ""
    url: ""
    signatureProfile: ""
    label: ""
    mobilePrefix: ""
  paypal:
    secret: ""
    clientId: ""
  invoice:
    company: ""
    address: ""
    country: ""
    email: ""
    postalCode: ""
    phoneCountryCode: ""
    phoneNationalNumber: ""
    bank: ""
    bankAccount: ""
    vatCode: ""
    paymentInterval: ""
  slurm:
    customerPrefix: ""
    projectPrefix: ""
    allocationPrefix: ""
  support:
    customBackend: ""
    servicedeskEmail: ""
    servicedeskToken: ""
    servicedeskUsername: ""
    servicedeskPassword: ""
    servicedeskUrl: ""
    organizationField: ""
    projectKey: ""
  marketplace:
    notify_staff: false
  pid_datacite:
    repository_id: ""
    password: ""
    prefix: ""
    url: ""
    publisher: ""
    collection_doi: ""
  uwsgi:
    plugins: python38
    processes: 16
  sentryDSN: ""
  whitelabeling:
    shortPageTitle: ""
    modePageTitle: ""
    loginLogoPath: ""
    sidebarLogoPath: ""
    poweredByLogoPath: ""
    faviconPath: ""
    tosHtmlPath: ""
    brandColor: ""
    heroImagePath: ""
    heroLinkLabel: ""
    heroLinkUrl: ""
    privacyHtmlPath: ""
    siteDescription: ""
  mastermindTemplating:
    mastermindTemplatesPath: "mastermind_templates"
  saml2:
    dir: "waldur_saml2"
    federations: []
  ssh_public_key_path: ""
  ssh_private_key_path: ""
  homeport:
    imageName: "opennode/waldur-homeport"
    googleAnalyticsID: ""
    userMandatoryFields: {}
    userRegistrationHiddenFields: {}
    docsLink: "https://docs.waldur.com"
    invitationCivilCodeHelpText: ""
  metricsExporter:
    enabled: false
  uvkEverypay:
    enabled: false
    uvkServer: "https://uvk-test.ut.ee/client/a74/server.php?format=JSON&action=uvk__"
    everypayGateway: "https://igw-demo.every-pay.com/api/v4"
    everypayUsername: ""
    everypayPassword: ""

bootstrap:
  enabled: false
  script: "bootstrap.sh"
  dir: "bootstrap"

postgresql:
  HAEnabled: false
  database: "waldur"
  username: "waldur"

postgresBackup:
  enabled: false
  schedule: "0 5 * * *"
  rotationSchedule: "0 6 * * 6"
  maxNumber: 10
  image: opennode/postgres-minio:0.1.0
  name: "waldur"

minio:
  accessKey: ""
  secretKey: ""
  bucketName: data
  ## min.io service endpoint used for communication inside a cluster
  endpoint: "http://minio.default.svc.cluster.local:9000" ## See docs/service-endpoint.md for details.

rabbitmq:
  user: "waldur"
  password: "waldur"
  ## hostname of rabbitmq service
  host: "rmq-rabbitmq.default.svc.cluster.local" ## See docs/service-endpoint.md for details.
  customManagementPort:
  customAMQPPort:

stressTesting:
  enabled: false
  locustFilePath: "locust_task/locust_test.py"

global:
  imageRegistry: "docker.io"
