# Default values for waldur.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

extraReplicas:
  celery:
  api:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

apiHostname: api.example.com
homeportHostname: web.example.com

affinity: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

hpa:
  api:
    enabled: false
    resources:
      requests:
        cpu: 500m
    cpuUtilizationBorder: 70
  celery:
    enabled: false
    workerResources:
      requests:
        cpu: 2000m
    beatResources:
      requests:
        cpu: 300m
    cpuUtilizationBorder: 80

nodeSelector: {}

tolerations: []

service:
  type: ClusterIP
  port: 80

storageClassName: local-storage

ingress:
  tls:
    source: "letsEncrypt" # Possible values: `letsEncrypt` and `secret`
    secretsDir: "tls"  # Enabled only if source == `secret`

logManagement:
  enabled: true
  elasticHost: "elasticsearch-master.elastic.svc.cluster.local" ## See docs/service-endpoint.md for details.
  elasticPort: "9200"
  elasticProtocol: "http"

waldur:
  imageTag: latest
  apiUrl: "https://api.example.com/"
  homeportUrl: ""
  emailHost: ""
  notificationSubject: ""
  timeZone: "UTC"
  features: []
  currencyName: "EUR"
  site:
    name: "Waldur"
    logo: ""
    address: ""
    email: ""
    phone: ""
  authMethods: 
    - LOCAL_SIGNIN
  facebook:
    secret: ""
    clientId: ""
  google:
    secret: ""
    clientId: ""
  smartid:
    secret: ""
    clientId: ""
  tara:
    secret: ""
    clientId: ""
  ldap:
    host: ""
    baseDN: ""
    userDN: ""
    user: ""
    password: ""
    admins: ""
    support: ""
  freeipa:
    hostname: ""
    password: ""
    username: ""
    verifySSL: ""
    groupnamePrefix: ""
    usernamePrefix: ""
  valimo:
    apId: ""
    apPwd: ""
    dnsname: ""
    url: ""
    signatureProfile: ""
    label: ""
    mobilePrefix: ""
  paypal:
    secret: ""
    clientId: ""
  analytics:
    databaseName: ""
  ansible:
    sshPublicKeyUUID: ""
  invoice:
    company: ""
    address: ""
    country: ""
    email: ""
    postalCode: ""
    phoneCountryCode: ""
    phoneNationalNumber: ""
    bank: ""
    bankAccount: ""
    vatCode: ""
    paymentInterval: ""
  slurm:
    customerPrefix: ""
    projectPrefix: ""
    allocationPrefix: ""
  support:
    customBackend: ""
    servicedeskEmail: ""
    servicedeskToken: ""
    servicedeskUsername: ""
    servicedeskPassword: ""
    servicedeskUrl: ""
    organizationField: ""
    projectKey: ""
    homeportIssueUrl: ""
  marketplace:
    openstack:
      instanceCategoryUUID: ""
      volumeCategoryUUID: ""
      tenantCategoryUUID: ""
  uwsgi:
    plugins: python36
    processes: 16
  sentryDSN: ""
  whitelabeling:
    shortPageTitle: ""
    modePageTitle: ""
    loginLogoUrl: ""
    loginLogoBlobPath: ""
    sidebarLogoUrl: ""
    sidebarLogoBlobPath: ""
    poweredByLogoUrl: ""
    poweredByLogoBlobPath: ""
    faviconPath: ""
    faviconBlobPath: ""
    manifestJsonPath: ""
    logo96Path: ""
    logo96BlobPath: ""
    logo144Path: ""
    logo144BlobPath: ""
    logo192Path: ""
    logo192BlobPath: ""
    tosHtmlPath: ""
    privacyHtmlPath: ""
  mastermindTemplating:
    mastermindTemplatesPath: "mastermind_templates"

postgresql:
  version: "12"
  postgresqlHost: waldur-postgres
  postgresqlDatabase: waldur
  postgresqlUsername: waldur
  replicaCount: 3
  storageClass: ""
  size: 10Gi
  loadBalancing:
    enableMaster: false
    enableReplica: false
  enableLogicalBackup: false

redis:
  enabled: true
  cluster:
    enabled: false
  nameOverride: waldur-redis
  # The following variables are only used when internal PG is disabled
  # host: redis
  # Just omit the password field if your redis cluster doesn't use password
  # password: redis
  # port: 6379
  # When defined the `password` field is ignored
  # existingSecret: secret-name
  # existingSecretKey: redis-password
  master:
    persistence:
      enabled: true
      # If change pvc size redis.master.persistence.size: 20Gi

##
## Storage configuration for waldur
persistence:
  ##
  ## enable persistance storage
  enabled: true
  ##
  ## Existing claim to use
  # existingClaim: nil
  ## Existing claim's subPath to use, e.g. "waldur" (optional)
  # subPath: ""
  ##
  ## Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  # storageClass: default
  accessMode: ReadWriteOnce
  ##
  ## Persistant storage size request
  size: 1Gi

minio:
  accessKey: ""
  secretKey: ""
  bucketName: data

  ## min.io service endpoint used for communication inside a cluster
  endpoint: "http://minio.default.svc.cluster.local:9000" ## See docs/service-endpoint.md for details.
