apiVersion: batch/v1
kind: Job
metadata:
  name: waldur-mastermind-job
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "waldur.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        "helm.sh/hook": post-install,post-upgrade
        "helm.sh/hook-weight": "0"
        "helm.sh/hook-delete-policy": hook-succeeded
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: waldur-mastermind-job
          image: opennode/waldur-mastermind:latest
          args:
            - "waldur"
            - "migrate"
            - "--noinput"
          env:
          - name: POSTGRES_USER
            value: "waldur"
          - name: POSTGRES_PASSWORD
            value: "waldur"
          - name: GLOBAL_SECRET_KEY
            value: "x2pYXyrAOwzXA2QOPzygIgkKFVMj/lUbZryWWbHoMtY="
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      restartPolicy: "Never"
