apiVersion: v1
kind: Service
metadata:
  name: waldur-db
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: waldur-db
