apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-waldur-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
