apiVersion: apps/v1
kind: Deployment
metadata:
  name: waldur-queue
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: waldur-queue
  template:
    metadata:
      labels:
        app: waldur-queue
    spec:
      containers:
        - name: redis
          image: bitnami/redis:latest
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          env:
          - name: ALLOW_EMPTY_PASSWORD
            value: "YES"
          volumeMounts:
            - name: redis
              mountPath: /bitnami/redis/conf/redis.conf
              subPath: redis.conf
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: redis
        configMap:
          name: redis-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

