apiVersion: v1
kind: Service
metadata:
  name: waldur-queue
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: waldur-queue
